### PR TITLE
Fix feature(core) and FromStr breaking changes.

### PR DESCRIPTION
**Pull request by alexchandel**
This needs a version bump, but it should be pushed to crates.io asap.

### CODE REVIEW

**Comment by alexchandel** [comment]
@BurntSushi Thoughts? It looks like Travis ran the wrong tests.

**Comment by alexchandel** [comment]
@BurntSushi I can bump the VN on this PR if you want.

**Comment by BurntSushi** [comment]
Thanks! Travis was running the right tests---it looks like you missed errors in the `docopt_macros` crate. I took care of them!

And don't worry about the version numbers. I have scripts that handle all that nonsense. :-)

**Comment by BurntSushi** [comment]
I've uploaded this fix to crates.io in `0.6.34`.

**Pull request merged**
