### PR TITLE
Fix for issue #196

### PR DESCRIPTION
**Pull request by fabricedesre**
Works for me, but I barely know what I'm doing ;)

### CODE REVIEW

**Comment by BurntSushi** [comment]
Awesome, thank you for fixing this! I'll put out a new release now.

**Comment by BurntSushi** [comment]
OK, `docopt_macros 0.6.86` is on crates.io. Thank again, I really appreciate it!

**Comment by fabricedesre** [comment]
Thanks for the quick review & merge & crate update!

**Pull request merged**
