### PR TITLE
Updated to latest rust

### PR DESCRIPTION
**Pull request by gchp**
This will require rustc-serialize to be updated first.
There is a PR which will fix the build here: https://github.com/rust-lang/rustc-serialize/pull/19

### CODE REVIEW

**Comment by gchp** [comment]
Updated with changes to `docopt_macros` too. Also, it appears that `rustc-serialize` has been updated, so this should build correctly now. Let me know if you need any updates!

**Comment by BurntSushi** [comment]
Fantastic, thank you!

**Comment by gchp** [comment]
@BurntSushi you're welcome!

**Comment by BurntSushi** [comment]
OK, I've pushed `0.6.26` to crates.io with this fix.

**Pull request merged**
