### PR TITLE
Update serialize

### PR DESCRIPTION
**Pull request by Hoverbear**
`rustc-serialize` hit 3.0.

### CODE REVIEW

**Comment by BurntSushi** [comment]
No. `rustc-serialize` `0.3.x` marks the start of using `std::io`. [It is still recommended to use `std::old_io`](http://doc.rust-lang.org/std/io/). That recommendation alone wouldn't stop me, but there is still no support for standard IO in `std::io`, so I can't transition everything over yet.

I think once [initial support](https://github.com/rust-lang/rust/pull/22797) gets into the next nightly, I'll be OK migrating.

**Comment by Hoverbear** [comment]
Okay, sounds good. I'm successfully using `0.3.x` in my projects right now on this branch if anyone else can't use docopt with their projects.

To anyone else:
If you see something like `Args does not implement Decodable` when trying to use Docopt feel free to switch to it.

**Comment by BurntSushi** [comment]
Ah sorry, I forgot to update this issue. Standard IO is now in `std::io`, so Docopt is on `rustc-serialize` `0.3.0` now: https://github.com/docopt/docopt.rs/pull/110

Note that you might still get this error if the reverse happens (you're pinned to `0.2.0`).

**Comment by Hoverbear** [comment]
Sweet!

**Pull request closed without merging**
