### PR TITLE
Update strsim to 0.5

### PR DESCRIPTION
**Pull request by dns2utf8**
Regards

### CODE REVIEW

**Comment by dns2utf8** [comment]
I requested a new build on travis. It seems to have failed somehow the first time.

**Comment by YetAnotherMinion** [comment]
@dns2utf8 you might want to go ahead and update to 0.5.1 while you are at it.

**Comment by dns2utf8** [comment]
Good point, done :smile:

**Comment by YetAnotherMinion** [comment]
@dns2utf8 Do you know who to ping to get feedback from the project maintainers about this pull request? I am very interested in getting this updated. Right now only 3 dependencies of Hyper introduce outdated further dependencies, and `strsim` is one of those.

**Comment by BurntSushi** [comment]
Sorry for the tardiness, but this looks good, thanks!

**Comment by dns2utf8** [comment]
You are welcome

**Comment by dns2utf8** [comment]
Thanks for the quick release :+1:

**Pull request merged**
