### PR TITLE
Update to rust master

### PR DESCRIPTION
**Pull request by alexcrichton**

### CODE REVIEW

**Comment by BurntSushi** [comment]
Thank you!

**Comment by BurntSushi** [comment]
@alexcrichton It looks like `derive(RustcDecodable)` doesn't work? I think this will be fixed in the next nightly?

**Comment by alexcrichton** [comment]
How so? It should be working today?

**Comment by BurntSushi** [comment]
Hmm, unless I'm doing something stupid...

```
[andrew@Liger docopt] rustc --version
rustc 0.13.0-nightly (ad9e75938 2015-01-05 00:26:28 +0000)
[andrew@Liger docopt] cargo clean
[andrew@Liger docopt] cargo update
    Updating registry `https://github.com/rust-lang/crates.io-index`
[andrew@Liger docopt] cargo test
   Compiling regex v0.1.8
   Compiling rustc-serialize v0.2.5
   Compiling docopt v0.6.23 (file:///home/andrew/data/projects/rust/docopt)
warning: using multiple versions of crate `regex`
/home/andrew/data/projects/rust/docopt/src/lib.rs:1:1: 1:1 note: used here
/home/andrew/data/projects/rust/docopt/src/lib.rs:1 //! Docopt for Rust. This implementation conforms to the
                                                    ^
note: crate name: regex
/home/andrew/data/projects/rust/docopt/src/lib.rs:221:1: 221:20 note: used here
/home/andrew/data/projects/rust/docopt/src/lib.rs:221 extern crate regex;
                                                      ^~~~~~~~~~~~~~~~~~~
note: crate name: regex
/home/andrew/data/projects/rust/docopt/examples/verbose_multiple.rs:22:10: 22:24 error: wrong number of type arguments: expected 0, found 1
/home/andrew/data/projects/rust/docopt/examples/verbose_multiple.rs:22 #[derive(RustcDecodable, Show)]
                                                                                ^~~~~~~~~~~~~~
note: in expansion of #[derive]
/home/andrew/data/projects/rust/docopt/examples/verbose_multiple.rs:22:1: 22:32 note: expansion site
Build failed, waiting for other jobs to finish...
/home/andrew/data/projects/rust/docopt/examples/decode.rs:25:10: 25:24 error: wrong number of type arguments: expected 0, found 1
/home/andrew/data/projects/rust/docopt/examples/decode.rs:25 #[derive(RustcDecodable, Show)]
                                                                      ^~~~~~~~~~~~~~
note: in expansion of #[derive]
/home/andrew/data/projects/rust/docopt/examples/decode.rs:25:1: 25:32 note: expansion site
/home/andrew/data/projects/rust/docopt/examples/cargo.rs:33:10: 33:24 error: wrong number of type arguments: expected 0, found 1
/home/andrew/data/projects/rust/docopt/examples/cargo.rs:33 #[derive(RustcDecodable, Show)]
                                                                     ^~~~~~~~~~~~~~
note: in expansion of #[derive]
/home/andrew/data/projects/rust/docopt/examples/cargo.rs:33:1: 33:32 note: expansion site
/home/andrew/data/projects/rust/docopt/examples/cp.rs:15:10: 15:24 error: wrong number of type arguments: expected 0, found 1
/home/andrew/data/projects/rust/docopt/examples/cp.rs:15 #[derive(RustcDecodable, Show)]
                                                                  ^~~~~~~~~~~~~~
note: in expansion of #[derive]
/home/andrew/data/projects/rust/docopt/examples/cp.rs:15:1: 15:32 note: expansion site
src/wordlist.rs:47:10: 47:24 error: wrong number of type arguments: expected 0, found 1
src/wordlist.rs:47 #[derive(RustcDecodable, Show)]
                            ^~~~~~~~~~~~~~
note: in expansion of #[derive]
src/wordlist.rs:47:1: 47:32 note: expansion site
Could not compile `docopt`.

To learn more, run the command again with --verbose.
```

**Comment by alexcrichton** [comment]
Is that the nightly compiler? This is what I get for the current nightly:

```
rustc 0.13.0-nightly (c7dd3c4d6 2015-01-05 23:51:00 +0000)
```

**Comment by BurntSushi** [comment]
Oh, whoa... I just force updated `rust-nightly-bin` and now I get:

```
[andrew@Liger ~] rustc --version
rustc 0.13.0-nightly (c7dd3c4d6 2015-01-05 23:51:00 +0000)
```

Weird. I had updated earlier this morning (maybe 9-10 hours ago?).

**Comment by BurntSushi** [comment]
OK, back in business. crates.io is updated. :-) Thanks!

**Comment by alexcrichton** [comment]
Weird... Maybe it was a mismatch for a bit with a futuristic date?

Magic!

**Pull request merged**
