### PR TITLE
rustup

### PR DESCRIPTION
**Pull request by nrc**

### CODE REVIEW

**Comment by nrc** [comment]
Sorry for the bustage in the parser. I'm afraid there might be more - we want to make the parser able to recover from errors, which is going to mean a lot of changes. I'll try and make the commit messages more informative, but ping me if you need help.

**Comment by BurntSushi** [comment]
@nrc My hero! Thank you! :D More informative commit messages would be much appreciated. :-)

**Comment by nrc** [comment]
There is an error, but I think that is because your CI is running Rust 1.1 instead of 1.5 for stable. The change which causes this error was just fixing a deprecation warning, so if you want to support 1.1, you could revert it.

**Comment by BurntSushi** [comment]
@nrc Yeah we can probably drop 1.1 at this point. Thanks!

**Pull request merged**
